<a href="https://colab.research.google.com/github/VIGNESHS2005/filpkart-sales-dataset-/blob/main/dataanalyst_loc1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [7]:
df=pd.read_csv('/content/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
df.loc[5,['Pclass','Name','Sex']]

Pclass                   3
Name      Moran, Mr. James
Sex                   male
Name: 5, dtype: object

In [10]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/flipkart_sales (1).csv')
df

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [12]:
df.loc[5,['Product Name','Price (INR)']]

Product Name    Mixer Grinder
Price (INR)          10475.03
Name: 5, dtype: object

In [13]:
print(df.columns)

Index(['Order ID', 'Product Name', 'Category', 'Price (INR)', 'Quantity Sold',
       'Total Sales (INR)', 'Order Date', 'Payment Method', 'Customer Rating'],
      dtype='object')

In [17]:
df.loc[5,['Product Name','Category','Quantity Sold','Order Date']]

Product Name      Mixer Grinder
Category         Home & Kitchen
Quantity Sold                 2
Order Date           2024-10-22
Name: 5, dtype: object

In [18]:
print(df.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [21]:
df.loc[[5,10,12,19],['Product Name','Price (INR)','Total Sales (INR)']]

        Product Name  Price (INR)  Total Sales (INR)
5      Mixer Grinder     10475.03           20950.06
10           Perfume     46409.57          232047.85
12  Educational Book      6670.82           33354.10
19           T-Shirt     32565.77          162828.85

In [22]:
df.loc[[5,10,12,19],['Product Name','Quantity Sold','Payment Method']]

        Product Name  Quantity Sold Payment Method
5      Mixer Grinder              2         Wallet
10           Perfume              5            UPI
12  Educational Book              5            COD
19           T-Shirt              5            COD

In [23]:
df.iloc[0:11:2,0::2]

    Order ID        Category  Quantity Sold  Order Date  Customer Rating
0   ORD00001           Books              2  2024-09-12              3.5
2   ORD00003          Beauty              4  2024-05-18              4.4
4   ORD00005  Home & Kitchen              3  2024-12-27              3.1
6   ORD00007        Clothing              3  2024-07-04              2.0
8   ORD00009        Clothing              2  2025-01-18              2.6
10  ORD00011          Beauty              5  2025-02-08              2.3

In [25]:
df.iloc[0:11:2,0::3]

    Order ID  Price (INR)  Order Date
0   ORD00001     49069.56  2024-09-12
2   ORD00003     11092.19  2024-05-18
4   ORD00005     26590.08  2024-12-27
6   ORD00007     38647.72  2024-07-04
8   ORD00009      1987.39  2025-01-18
10  ORD00011     46409.57  2025-02-08